export const DeliveryEventType = {
  DELIVERY_ASSIGNED: "DELIVERY_ASSIGNED",
  LOADING_STARTED: "LOADING_STARTED",
  DRIVER_EN_ROUTE: "DRIVER_EN_ROUTE",
  DRIVER_ARRIVED: "DRIVER_ARRIVED",
  MEASUREMENT_STARTED: "MEASUREMENT_STARTED",
  MEASUREMENT_COMPLETED: "MEASUREMENT_COMPLETED",
  DELIVERY_COMPLETED: "DELIVERY_COMPLETED",
  DELIVERY_FAILED: "DELIVERY_FAILED",
  DELIVERY_SKIPPED: "DELIVERY_SKIPPED",
} as const;

export type DeliveryEventType =
  (typeof DeliveryEventType)[keyof typeof DeliveryEventType];
